services:
  agent:
    container_name: noattack_agent
    build: .
    depends_on:
      - redis
    network_mode: host
    volumes:
      - .:/app

  redis:
    container_name: noattack_redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
